# Generated by Django 3.2.7 on 2021-09-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='author_first_name',
            field=models.CharField(default='Test', max_length=1024),
        ),
        migrations.AddField(
            model_name='article',
            name='author_last_name',
            field=models.CharField(default='Test', max_length=1024),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('HL', 'Helth'), ('ACT', 'Actuality'), ('SP', 'Sport'), ('POL', 'Politics'), ('ENTM', 'Entertainment'), ('HS', 'History'), ('LTR', 'Literature')], default='ACT', max_length=4),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='alt', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(auto_created=True, default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
