# Generated by Django 3.2.7 on 2021-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210913_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='title', unique=True),
        ),
    ]
