# Generated by Django 3.2.7 on 2021-09-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210913_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_first_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_last_name',
            field=models.CharField(max_length=1024),
        ),
    ]
