# Generated by Django 3.2.7 on 2021-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210913_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_first_name',
            new_name='authors',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_last_name',
        ),
    ]
