# Generated by Django 3.2.7 on 2021-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210921_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='authors_image',
        ),
        migrations.AddField(
            model_name='article',
            name='content_image',
            field=models.ImageField(default='alt', upload_to='images/'),
        ),
    ]
