# Generated by Django 3.2.7 on 2021-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210921_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('HL', 'Health'), ('ACT', 'Actuality'), ('SP', 'Sport'), ('POL', 'Politics'), ('ENTM', 'Entertainment'), ('HS', 'History'), ('LTR', 'Literature')], default='ACT', max_length=4),
        ),
    ]
