# Generated by Django 3.2.7 on 2021-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
