# Generated by Django 3.2.7 on 2021-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_authors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
