# Generated by Django 3.2.7 on 2021-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
